### ISSUE TITLE
Sat>ip

### ISSUE THREAD

**Issue by estimadarocha** [lapicidae/vdr-server#1]
is it possible to add the possibilie to run it as a server pushing from sat>ip server?

**Comment by lapicidae** [comment]
You can use the VDR plugin [satip](https://github.com/rofafor/vdr-plugin-satip) via the "PLUGINS" environment variable. The plugin will be installed at startup via vdr4arch repository.

**Comment by estimadarocha** [comment]
And how do i make my initial channel scan???

**Comment by lapicidae** [comment]
I do not have a satip setup.
But i think, plugin [channelscan](https://bitbucket.org/ua0lnj/channelscan/src/master/) should do the trick ([VDR-Wiki](https://www.linuxtv.org/vdrwiki/index.php/Channelscan-plugin)).

OSD is available via "WebUi -> remote".

**Comment by estimadarocha** [comment]
Sorry i am really really new on VDR. OSD means??? Whats the port of webui?

**Comment by lapicidae** [comment]
Webui can be found at "http://<your-ip>:8008" in default setup.
[OSD](https://www.linuxtv.org/vdrwiki/index.php/OSD) ;-)

[VDR Wiki](https://www.linuxtv.org/vdrwiki/index.php/Main_Page) and the [VDR International Forum](https://www.vdr-portal.de/forum/index.php?board/79-international/) are also very helpful.

**Comment by estimadarocha** [comment]
Starting vdr...,
vdr: cap_set_proc failed: Operation not permitted

**Comment by estimadarocha** [comment]
Starting vdr...,
vdr: no primary device found - using first device!,
user.err: Dec  5 22:02:33 vdr: [1494] ERROR: invalid primary device number: 1,
user.err: Dec  5 22:02:33 vdr: [1494] ERROR: no primary device found - using first device!,

**Comment by lapicidae** [comment]
### Sorry for my late reply!

**ERROR: invalid primary device number:**
This should not appear if you have "satip" plugin enabled.
Please use, for example, "PLUGINS=live satip streamdev-server" environment variable.

**ERROR: no OSD provider available - using dummy OSD!**
**ERROR: Channel locked (recording)!**
Can be ignored with a headless VDR.

**warning: directory permissions differ on**
Will be fixed in the next commit, but VDR should work fine anyway.

**Comment by estimadarocha** [comment]
@lapicidae do you have any form of direct contact? 

i guess you are also missing some docker capabilities!

**Comment by estimadarocha** [comment]
this happen a lot...

Starting vdr...
user.err: Dec 29 15:56:42 vdr: [4099] ERROR: /usr/lib/vdr/plugins/libvdr-channelscan.so.2.4.7: cannot open shared object file: No such file or directory
vdr: /usr/lib/vdr/plugins/libvdr-channelscan.so.2.4.7: cannot open shared object file: No such file or directory
Starting vdr...
vdr: /usr/lib/vdr/plugins/libvdr-channelscan.so.2.4.7: cannot open shared object file: No such file or directory
user.err: Dec 29 15:56:43 vdr: [4102] ERROR: /usr/lib/vdr/plugins/libvdr-channelscan.so.2.4.7: cannot open shared object file: No such file or directory
Starting vdr...

**Comment by lapicidae** [comment]
@estimadarocha
You can contact me via email, but my response time won't be much faster :wink:
[LINK](https://cryptobin.co/03w6f9u7) (link will expire in 1 week and password is your github username)

>...--cap-add=SYS_NICE and SYS_TIME

I don't think the VDR should be able to change the Docker host's system time.
However, I will change the readme to add a note about "VDR SetSystemTime" and "docker cap SYS_NICE & SYS_TIME".

>..libvdr-channelscan.so.2.4.7: cannot open shared object file..

The arch Docker image and the VDR4Arch repository seem, once again, to be at different levels.
For this reason I am currently working on a change to an AUR based image.
You could try to pull the latest image... or rebuild the image.

> PGID=${PGID:-666}
>is it supposed to be like that?

yes it is:
`FOO="${VARIABLE:-default}"  # If variable not set or null, use default.`

**Comment by estimadarocha** [comment]
vdr: cap_set_proc failed: Operation not permitted
VDR exit code: 2
