### ISSUE TITLE
VDR is not starting

### ISSUE THREAD

**Issue by Borgal77** [lapicidae/vdr-server#17]
The VDR crashes after starting.  Last Update from 22.02.23 - 09:19 PM

user.err: Feb 22 21:49:27 vdr: [25569] ERROR: video data stream broken
user.err: Feb 22 21:49:27 vdr: [25569] initiating emergency exit
user.err: Feb 22 21:49:27 vdr: [25499] emergency exit requested - shutting down
user.info: Feb 22 21:49:28 vdr: [25499] DDCI-Inf: plugin stopped
user.err: Feb 22 21:49:32 vdr: [25499] emergency exit!
VDR exit code: 1

regards
Lars

**Comment by Borgal77** [comment]
i have checked again, after i stopt the timer the VDR is still running.

┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄⚟ Start VDR ⚞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
user.info: Feb 22 21:59:57 vdr: [26615] DDCI-Inf: plugin version 1.0.5 initializing (compiled for VDR version 2.6.3)
user.info: Feb 22 21:59:57 vdr: [26615] DDCI-Inf: found 2 DD CI adapters
user.info: Feb 22 21:59:57 vdr: [26615] DDCI-Inf: Creating DdCiAdapter 0 (/dev/dvb/adapter4/ca0)
user.info: Feb 22 21:59:57 vdr: [26615] DDCI-Inf: Creating DdCiAdapter 1 (/dev/dvb/adapter5/ca0)
user.info: Feb 22 21:59:57 vdr: [26615] DDCI-Inf: plugin started
user.err: Feb 22 21:59:58 vdr: [26638] live: INFO: attempt to listen on ip = ''
user.err: Feb 22 22:00:02 vdr: [26615] ERROR: no OSD provider available - using dummy OSD!
user.notice: Feb 22 22:00:03 recordingaction: executing /etc/vdr/recording-hooks/R60.copy_epgimage BEFORE recording /srv/vdr/video/.....rec as shell script
user.notice: Feb 22 22:00:03 recordingaction: copy-epgimage is disabled
user.notice: Feb 22 22:00:03 recordingaction: executing /etc/vdr/recording-hooks/R90.custom BEFORE recording /srv/vdr/video/.....rec as shell script
user.err: Feb 22 22:00:04 vdr: [26615] ERROR: Kanal blockiert (zeichnet auf)!
user.notice: Feb 22 22:00:07 recordingaction: executing /etc/vdr/recording-hooks/R60.copy_epgimage BEFORE recording /srv/vdr/video/.....rec as shell script
user.notice: Feb 22 22:00:07 recordingaction: copy-epgimage is disabled
user.notice: Feb 22 22:00:07 recordingaction: executing /etc/vdr/recording-hooks/R90.custom BEFORE recording /srv/vdr/video/.....rec as shell script
user.err: Feb 22 22:00:14 vdr: [26615] ERROR: no OSD provider available - using dummy OSD!
user.err: Feb 22 22:00:37 vdr: [26685] ERROR: video data stream broken
user.err: Feb 22 22:00:37 vdr: [26685] initiating emergency exit
user.err: Feb 22 22:00:37 vdr: [26615] emergency exit requested - shutting down
user.info: Feb 22 22:00:39 vdr: [26615] DDCI-Inf: plugin stopped
user.err: Feb 22 22:00:40 vdr: [26615] emergency exit!
VDR exit code: 1

**Comment by Borgal77** [comment]
Even with a new timer, the VDR continues to run, so the topic can be closed.

**Comment by lapicidae** [comment]
This problem appears, in my experience, when several encrypted channels are recorded simultaneously but only one can be decrypted.
I suspect this is due to the interaction of dvbapi and ddci or just the dvbapi plugin.

If dvbapi is not active, then VDR should warn about such timer overlaps (as far as I know).
