### ISSUE TITLE
Owner issue with /etc/msmtprc

### ISSUE THREAD

**Issue by michi1972-dev** [lapicidae/vdr-server#23]
As of a security issue to msmtp this only works now, if ownership is correct. I have to chown to vdr anytime container is created. kind of annoying. what can i do?

root@nas:/zfs-pool/container-data/vdr/system# docker exec -it -u root vdr-server /bin/bash
[root@nas vdr]# ls -lha /etc/msmtprc 
-rw-r----- 1 root root 558 Mar 24 14:30 /etc/msmtprc
[root@nas vdr]# chown vdr:root /etc/msmtprc 
[root@nas vdr]# ls -lha /etc/msmtprc 
-rw-r----- 1 vdr root 558 Mar 24 14:30 /etc/msmtprc
[root@nas vdr]#

**Comment by lapicidae** [comment]
Thank you for your advice!

I will make the following changes:

- the group ownership on the file '/etc/msmtprc' is changed to 'mail' 
- the user 'vdr' will be added to the 'mail' group

This should solve the problem :-)

**Comment by michi1972-dev** [comment]
Thank you so much! Next night my NAS will pull the new version and will rebuid the container. I'm pretty sure it'll work well. I love the epgsearch mails.

Good work!
