### ISSUE TITLE
markad "bootloop"

### ISSUE THREAD

**Issue by michi1972-dev** [lapicidae/vdr-server#28]
> ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄⚟ Start VDR ⚞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
markad: unrecognized option '--cDecoder'
VDR exit code: 2
┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄⚟ Start VDR ⚞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄

This pops up with the newest update. Seems to be uptream error.

What can i do?

**Comment by lapicidae** [comment]
I'm not sure and can't test it myself until tomorrow, but have you tried removing the parameter ‘cDecoder’ from the file ‘VDR/system/conf.d/50-markad.conf’ (or something similar)?

**Comment by michi1972-dev** [comment]
Almost going to sleep ... Had a quick look, but is almost an emtpy file:

`#
# markad VDR plugin arguments
#

[markad]

`

nothing else inside. Any ideas?

**Comment by lapicidae** [comment]
On my test system, VDR including the markad plugin starts without any problems.

**Are you using the latest image?**
By the way, a new one has just been created.

For testing you could also start with other/empty configuration directories (‘_/vdr/config_’ & ‘_/vdr/system_’).
But please do not forget the backup. :no_mouth:
