### ISSUE TITLE
Passing parameters to plugins

### ISSUE THREAD

**Issue by jerkball** [lapicidae/vdr-server#3]
Thank you very much for you work dockerizing vdr...

I'm trying to you satip for my docker vdr, as my box got no dvb hardware....

In docker host-mode, my minisat with 4 tuners got found but channelscan with plugins wirbelscan or channelscan doesn't change the channels.conf (permissions seem to be right, as i can wright the file via docker console and user vdr)

Neither do dvbapi recognize any CA PMT data on crypted channels.

Now I try to define the satip tuners by myself via parameters given tu vdr start command.

But I don't know how to pass those parameters to vdr start...

Do I need to quote around the plugin definition in my docker-compose file?

I tried to use "command" in docker-compose, but that did not the trick.

Do you have an advice for my situation? :-)

Greetings

JERKBALL

**Comment by jerkball** [comment]
As always... digging around 2 days around that problem, but when I start that issue, the problem solves by itself...

Partialy at least... The CA PMT thing and scanning was due to my old firmware on my satip server Telestar Digibit R1... custom firmware got its last update 2018... but now i found a fork by Jalle19 which has newest minisatip daemon and now it works as expected...

Just the thing with passing parameters of plugins whould be still good to know :-)

So just close this issue, weather you know the answer or not... maybe my explenation helps anyone, having this issue too...

Thanks a lot...

**Comment by lapicidae** [comment]
Hi,
Plugin parameters are passed via the corresponding file in "vdr/system/conf.d/".
I will add a note to the readme regarding this.
